name: gha_workflow:Zadanie2

on:
  workflow_dispatch:

env:
  MAJOR_VERSION: 1
  MINOR_VERSION: 0

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Instalacja środowiska Docker + Buildx
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2
        
      # Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: czajkakacper
          password: ${{ secrets.GH_ZADANIE}}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      # Budowa obrazu dla dwóch architektur sprzętowych 
      # oraz przesłanie do własnego repo na Dockerhub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/x86_64,linux/arm64/v8 
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=inline,src=/tmp/.buildx-cache # cache - inline
          cache-to: type=inline,mode=max,dest=/tmp/.buildx-cache-new # cache - inline
          tags: |
            ghcr.io/${{ github.repository_owner }}/chmurowezad2img:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.x86_64
            ghcr.io/${{ github.repository_owner }}/chmurowezad2img:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.arm64
          # tags: |
          #   ghcr.io/${{ github.repository_owner }}/chmurowezad2img:x86_64
          #   ghcr.io/${{ github.repository_owner }}/chmurowezad2img:arm64
          
      - name: Increment version
        run: |
          MAJOR_VERSION=$(echo $MAJOR_VERSION | awk -F"." '{print $1}')
          MINOR_VERSION=$(echo $MINOR_VERSION | awk -F"." '{print $1}')
          MAJOR_VERSION=$((MAJOR_VERSION + 1))
          MINOR_VERSION=$((MINOR_VERSION + 1))
          sed -i "s/MAJOR_VERSION=.*/MAJOR_VERSION=$MAJOR_VERSION/" $GITHUB_ENV
          sed -i "s/MINOR_VERSION=.*/MINOR_VERSION=$MINOR_VERSION/" $GITHUB_ENV

      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache  